sudo: required
services:
  - docker

before_install:
  - docker build -t risabhsharma71/docker-react -f Dockerfile.dev .

script:
  - docker run risabhsharma71/docker-react npm run test -- --coverage
